name: tdd_clean_architecture
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http: ^1.2.2
  connectivity: ^3.0.6
  shared_preferences: ^2.3.2
  dartz:
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


